spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/steamz
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:migration
  mail:
    host: poczta.o2.pl
    port: 587
    username: piotrk322@o2.pl
    password: Dupacyce1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  price-alert:
    threshold: 0.01  # 1% difference