spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/steamz
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:migration

sendgrid:
  api-key: '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'  # Be sure to replace this with your actual SendGrid API key

app:
  price-alert:
    threshold: 0.01  # 1% difference

steam:
  api:
    base-url: "https://steamcommunity.com/market/priceoverview/"
    country: "PL"
    currency: 6
    appid: 730